
/**
 ** @Author:pandayu
 ** @Version:1.0
 ** @DateTime:2018-09-09
 ** @Project:pandaCard CardGame
 ** @Contact: QQ:815099602
 **/
 var ATTRIBUTEIDCFG = {
    "1":{
      "attributeid":1,
      "attributename":"hp",
      "describe":"生命"
    },
    "2":{
      "attributeid":2,
      "attributename":"atk",
      "describe":"攻击"
    },
    "3":{
      "attributeid":3,
      "attributename":"def",
      "describe":"防御"
    },
    "4":{
      "attributeid":4,
      "attributename":"allhp",
      "describe":"全队生命"
    },
    "5":{
      "attributeid":5,
      "attributename":"allatk",
      "describe":"全队攻击"
    },
    "6":{
      "attributeid":6,
      "attributename":"alldef",
      "describe":"全队防御"
    },
    "13":{
      "attributeid":13,
      "attributename":"atkspeed",
      "describe":"攻击速度"
    },
    "14":{
      "attributeid":14,
      "attributename":"basecrit",
      "describe":"重伤"
    },
    "15":{
      "attributeid":15,
      "attributename":"baseuncrit",
      "describe":"重伤抵抗"
    },
    "16":{
      "attributeid":16,
      "attributename":"basecritvalue",
      "describe":"重伤倍率"
    },
    "17":{
      "attributeid":17,
      "attributename":"basehit",
      "describe":"命中"
    },
    "18":{
      "attributeid":18,
      "attributename":"basemiss",
      "describe":"闪避"
    },
    "19":{
      "attributeid":19,
      "attributename":"basedamage",
      "describe":"伤害加成"
    },
    "20":{
      "attributeid":20,
      "attributename":"baseinjury",
      "describe":"免伤加成"
    },
    "21":{
      "attributeid":21,
      "attributename":"baserestored",
      "describe":"回复率"
    },
    "22":{
      "attributeid":22,
      "attributename":"baseberestored",
      "describe":"被回复率"
    },
    "23":{
      "attributeid":23,
      "attributename":"skilldamage",
      "describe":"技能伤害"
    },
    "24":{
      "attributeid":24,
      "describe":"PVP伤害加成"
    },
    "25":{
      "attributeid":25,
      "describe":"pvp伤害减免"
    },
    "29":{
      "attributeid":29,
      "describe":"全队重伤"
    },
    "30":{
      "attributeid":30,
      "describe":"全队重伤抵抗"
    },
    "31":{
      "attributeid":31,
      "describe":"全队命中"
    },
    "32":{
      "attributeid":32,
      "describe":"全队闪避"
    },
    "33":{
      "attributeid":33,
      "describe":"全队伤害加成"
    },
    "34":{
      "attributeid":34,
      "describe":"全队免伤加成"
    }
  }