
/**
 ** @Author:pandayu
 ** @Version:1.0
 ** @DateTime:2018-09-09
 ** @Project:pandaCard CardGame
 ** @Contact: QQ:815099602
 **/
 var BUFFCFG = {
    "1":{
      "id":1,
      "name":"攻速提高（自身）",
      "b_type":1,
      "s_type":13,
      "sup_type":0,
      "data_type":1,
      "data_source":1,
      "cal_type":2,
      "data_value":13,
      "end_type":1
    },
    "2":{
      "id":2,
      "name":"眩晕",
      "b_type":0,
      "s_type":1003,
      "sup_type":0,
      "data_type":0,
      "data_source":0,
      "cal_type":0,
      "data_value":0,
      "end_type":1
    },
    "3":{
      "id":3,
      "name":"全队攻击",
      "b_type":1,
      "s_type":5,
      "sup_type":0,
      "data_type":2,
      "data_source":2,
      "cal_type":2,
      "data_value":2,
      "end_type":1
    },
    "4":{
      "id":4,
      "name":"全队防御",
      "b_type":1,
      "s_type":6,
      "sup_type":0,
      "data_type":2,
      "data_source":2,
      "cal_type":2,
      "data_value":3,
      "end_type":1
    },
    "5":{
      "id":5,
      "name":"受伤增加",
      "b_type":0,
      "s_type":20,
      "sup_type":0,
      "data_type":1,
      "data_source":2,
      "cal_type":2,
      "data_value":20,
      "end_type":1
    },
    "6":{
      "id":6,
      "name":"闪避",
      "b_type":1,
      "s_type":18,
      "sup_type":0,
      "data_type":2,
      "data_source":1,
      "cal_type":2,
      "data_value":18,
      "end_type":1
    },
    "7":{
      "id":7,
      "name":"防御（自身）",
      "b_type":1,
      "s_type":3,
      "sup_type":0,
      "data_type":2,
      "data_source":1,
      "cal_type":2,
      "data_value":3,
      "end_type":1
    },
    "8":{
      "id":8,
      "name":"防御（目标）",
      "b_type":1,
      "s_type":3,
      "sup_type":0,
      "data_type":2,
      "data_source":2,
      "cal_type":2,
      "data_value":3,
      "end_type":1
    },
    "9":{
      "id":9,
      "name":"减伤（自身）",
      "b_type":1,
      "s_type":20,
      "sup_type":0,
      "data_type":1,
      "data_source":1,
      "cal_type":2,
      "data_value":20,
      "end_type":1
    },
    "10":{
      "id":10,
      "name":"减伤（目标）",
      "b_type":1,
      "s_type":20,
      "sup_type":0,
      "data_type":1,
      "data_source":2,
      "cal_type":2,
      "data_value":20,
      "end_type":1
    },
    "11":{
      "id":11,
      "name":"攻速降低",
      "b_type":0,
      "s_type":13,
      "sup_type":0,
      "data_type":1,
      "data_source":2,
      "cal_type":2,
      "data_value":13,
      "end_type":1
    },
    "12":{
      "id":12,
      "name":"伤害提高（自身）",
      "b_type":1,
      "s_type":19,
      "sup_type":0,
      "data_type":1,
      "data_source":1,
      "cal_type":2,
      "data_value":19,
      "end_type":1
    },
    "13":{
      "id":13,
      "name":"伤害提高（目标）",
      "b_type":1,
      "s_type":19,
      "sup_type":0,
      "data_type":1,
      "data_source":2,
      "cal_type":2,
      "data_value":19,
      "end_type":1
    },
    "14":{
      "id":14,
      "name":"攻击（自身）",
      "b_type":1,
      "s_type":2,
      "sup_type":0,
      "data_type":2,
      "data_source":1,
      "cal_type":2,
      "data_value":2,
      "end_type":1
    },
    "15":{
      "id":15,
      "name":"攻击（目标）",
      "b_type":1,
      "s_type":2,
      "sup_type":0,
      "data_type":2,
      "data_source":2,
      "cal_type":2,
      "data_value":2,
      "end_type":1
    },
    "16":{
      "id":16,
      "name":"防御（自身）",
      "b_type":1,
      "s_type":3,
      "sup_type":0,
      "data_type":2,
      "data_source":1,
      "cal_type":2,
      "data_value":3,
      "end_type":1
    },
    "17":{
      "id":17,
      "name":"防御（目标）",
      "b_type":1,
      "s_type":3,
      "sup_type":0,
      "data_type":2,
      "data_source":2,
      "cal_type":2,
      "data_value":3,
      "end_type":1
    },
    "18":{
      "id":18,
      "name":"暴击几率（自身）",
      "b_type":1,
      "s_type":14,
      "sup_type":0,
      "data_type":1,
      "data_source":1,
      "cal_type":2,
      "data_value":14,
      "end_type":1
    },
    "19":{
      "id":19,
      "name":"无敌",
      "b_type":1,
      "s_type":1001,
      "sup_type":0,
      "data_type":0,
      "data_source":0,
      "cal_type":0,
      "data_value":0,
      "end_type":1
    },
    "20":{
      "id":20,
      "name":"攻击降低",
      "b_type":0,
      "s_type":2,
      "sup_type":0,
      "data_type":2,
      "data_source":2,
      "cal_type":2,
      "data_value":2,
      "end_type":1
    },
    "21":{
      "id":21,
      "name":"沉默",
      "b_type":0,
      "s_type":1005,
      "sup_type":0,
      "data_type":0,
      "data_source":0,
      "cal_type":0,
      "data_value":0,
      "end_type":1
    },
    "22":{
      "id":22,
      "name":"攻速降低",
      "b_type":0,
      "s_type":13,
      "sup_type":0,
      "data_type":1,
      "data_source":1,
      "cal_type":2,
      "data_value":13,
      "end_type":1
    }
  }