
/**
 ** @Author:pandayu
 ** @Version:1.0
 ** @DateTime:2018-09-09
 ** @Project:pandaCard CardGame
 ** @Contact: QQ:815099602
 **/
 var COMMANDERSKILLCFG = {
    "101":{
      "commanderskillid":101,
      "commanderskillname":"基础攻击",
      "icon":"jineng_002.png",
      "eff":[0,"null"],
      "describle":"为全体出战部队增加$1点攻击",
      "uidescrible":"攻击",
      "skillcd":0,
      "skilltime":0,
      "attributeid":2,
      "bufftype":0,
      "skilltype":1,
      "mostlv":1600
    },
    "102":{
      "commanderskillid":102,
      "commanderskillname":"强化攻击",
      "icon":"jineng_013.png",
      "eff":[0,"null"],
      "describle":"为全体出战部队增加$1的攻击",
      "uidescrible":"攻击",
      "skillcd":0,
      "skilltime":0,
      "attributeid":2,
      "bufftype":0,
      "skilltype":1,
      "mostlv":16
    },
    "103":{
      "commanderskillid":103,
      "commanderskillname":"强化防御",
      "icon":"jineng_003.png",
      "eff":[0,"null"],
      "describle":"为全体出战部队增加$1的防御",
      "uidescrible":"防御",
      "skillcd":0,
      "skilltime":0,
      "attributeid":3,
      "bufftype":0,
      "skilltype":1,
      "mostlv":16
    },
    "104":{
      "commanderskillid":104,
      "commanderskillname":"强化生命",
      "icon":"jineng_008.png",
      "eff":[0,"null"],
      "describle":"为全体出战部队增加$1的生命",
      "uidescrible":"生命",
      "skillcd":0,
      "skilltime":0,
      "attributeid":1,
      "bufftype":0,
      "skilltype":1,
      "mostlv":16
    },
    "105":{
      "commanderskillid":105,
      "commanderskillname":"强化重伤",
      "icon":"jineng_009.png",
      "eff":[0,"null"],
      "describle":"为全体出战部队增加$1的重伤概率",
      "uidescrible":"重伤",
      "skillcd":0,
      "skilltime":0,
      "attributeid":14,
      "bufftype":0,
      "skilltype":1,
      "mostlv":16
    },
    "106":{
      "commanderskillid":106,
      "commanderskillname":"强化命中",
      "icon":"jineng_006.png",
      "eff":[0,"null"],
      "describle":"为全体出战部队增加$1的命中率",
      "uidescrible":"命中",
      "skillcd":0,
      "skilltime":0,
      "attributeid":17,
      "bufftype":0,
      "skilltype":1,
      "mostlv":16
    },
    "107":{
      "commanderskillid":107,
      "commanderskillname":"强化闪避",
      "icon":"jineng_007.png",
      "eff":[0,"null"],
      "describle":"为全体出战部队增加$1的闪避率",
      "uidescrible":"闪避",
      "skillcd":0,
      "skilltime":0,
      "attributeid":18,
      "bufftype":0,
      "skilltype":1,
      "mostlv":16
    },
    "108":{
      "commanderskillid":108,
      "commanderskillname":"机关枪",
      "icon":"jineng_001.png",
      "eff":[1,"amm_rif_bic01"],
      "describle":"召唤一架机枪塔攻击敌军，每秒发射10颗子弹，每颗子弹造成$1点伤害，持续10秒。可手动控制机枪塔的攻击方向",
      "uidescrible":"伤害",
      "skillcd":300,
      "skilltime":10,
      "attributeid":23,
      "bufftype":0,
      "skilltype":2,
      "mostlv":30
    },
    "109":{
      "commanderskillid":109,
      "commanderskillname":"导弹发射",
      "icon":"jineng_010.png",
      "eff":[1,"amm_rif_bic01"],
      "describle":"向指定区域发射1发导弹，对3*3范围内敌人造成$1点伤害",
      "uidescrible":"伤害",
      "skillcd":600,
      "skilltime":1,
      "attributeid":23,
      "bufftype":0,
      "skilltype":2,
      "mostlv":30
    },
    "110":{
      "commanderskillid":110,
      "commanderskillname":"鼓舞士气",
      "icon":"jineng_004.png",
      "eff":[2,"buff_spe01"],
      "describle":"提升全军$1点攻击速度，持续30秒",
      "uidescrible":"攻速",
      "skillcd":1800,
      "skilltime":30,
      "attributeid":13,
      "bufftype":0,
      "skilltype":2,
      "mostlv":11
    },
    "111":{
      "commanderskillid":111,
      "commanderskillname":"暴击力量",
      "icon":"jineng_012.png",
      "eff":[2,"buff_cri01"],
      "describle":"提升我方全体$1的暴击，后排士兵攻击血量最多的敌军，持续30秒",
      "uidescrible":"重伤",
      "skillcd":1800,
      "skilltime":30,
      "attributeid":14,
      "bufftype":2,
      "skilltype":2,
      "mostlv":16
    },
    "112":{
      "commanderskillid":112,
      "commanderskillname":"全军突击",
      "icon":"jineng_011.png",
      "eff":[2,"buff_def01"],
      "describle":"提升我方全体$1的伤害，前排士兵附带嘲讽。持续30秒，",
      "uidescrible":"伤害",
      "skillcd":1800,
      "skilltime":30,
      "attributeid":19,
      "bufftype":1,
      "skilltype":2,
      "mostlv":16
    }
  }