
/**
 ** @Author:pandayu
 ** @Version:1.0
 ** @DateTime:2018-09-09
 ** @Project:pandaCard CardGame
 ** @Contact: QQ:815099602
 **/
 var INTERFACECFG = {
    "1":{
      "inid":1,
      "type":2,
      "vip":0,
      "level":15,
      "name":"竞技场"
    },
    "2":{
      "inid":2,
      "type":2,
      "vip":0,
      "level":40,
      "name":"军事活动-普通副本"
    },
    "3":{
      "inid":3,
      "type":2,
      "vip":0,
      "level":45,
      "name":"军神争霸"
    },
    "4":{
      "inid":4,
      "type":2,
      "vip":0,
      "level":40,
      "name":"军团大厅"
    },
    "5":{
      "inid":5,
      "type":2,
      "vip":0,
      "level":1,
      "name":"名人堂"
    },
    "6":{
      "inid":6,
      "type":2,
      "vip":0,
      "level":7,
      "name":"兵工厂"
    },
    "7":{
      "inid":7,
      "type":2,
      "vip":0,
      "level":18,
      "name":"王牌雕像"
    },
    "8":{
      "inid":8,
      "type":2,
      "vip":0,
      "level":50,
      "name":"士兵觉醒"
    },
    "9":{
      "inid":9,
      "type":2,
      "vip":0,
      "level":55,
      "name":"士兵改造"
    },
    "10":{
      "inid":10,
      "type":2,
      "vip":0,
      "level":2,
      "name":"部队"
    },
    "11":{
      "inid":11,
      "type":2,
      "vip":0,
      "level":5,
      "name":"士兵进阶"
    },
    "12":{
      "inid":12,
      "type":2,
      "vip":0,
      "level":10,
      "name":"士兵突破"
    },
    "13":{
      "inid":13,
      "type":2,
      "vip":0,
      "level":3,
      "name":"兵营"
    },
    "14":{
      "inid":14,
      "type":2,
      "vip":0,
      "level":4,
      "name":"高级研发"
    },
    "15":{
      "inid":15,
      "type":2,
      "vip":0,
      "level":8,
      "name":"回收"
    },
    "16":{
      "inid":16,
      "type":2,
      "vip":0,
      "level":30,
      "name":"协同作战"
    },
    "17":{
      "inid":17,
      "type":2,
      "vip":0,
      "level":6,
      "name":"快速战斗"
    },
    "18":{
      "inid":18,
      "type":2,
      "vip":0,
      "level":17,
      "name":"普通侦查"
    },
    "19":{
      "inid":19,
      "type":2,
      "vip":0,
      "level":60,
      "name":"精英侦查"
    },
    "20":{
      "inid":20,
      "type":2,
      "vip":0,
      "level":5,
      "name":"日常任务"
    },
    "21":{
      "inid":21,
      "type":2,
      "vip":0,
      "level":18,
      "name":"排行榜"
    },
    "22":{
      "inid":22,
      "type":2,
      "vip":0,
      "level":45,
      "name":"聊天"
    },
    "23":{
      "inid":23,
      "type":2,
      "vip":0,
      "level":12,
      "name":"好友"
    },
    "24":{
      "inid":24,
      "type":2,
      "vip":0,
      "level":60,
      "name":"资源掠夺"
    },
    "25":{
      "inid":25,
      "type":2,
      "vip":0,
      "level":60,
      "name":"士兵图鉴"
    },
    "26":{
      "inid":26,
      "type":2,
      "vip":0,
      "level":60,
      "name":"boss入侵"
    },
    "27":{
      "inid":27,
      "type":2,
      "vip":0,
      "level":43,
      "name":"装备锻造"
    },
    "28":{
      "inid":28,
      "type":2,
      "vip":0,
      "level":65,
      "name":"指挥官座驾"
    },
    "29":{
      "inid":29,
      "type":2,
      "vip":0,
      "level":60,
      "name":"敌将来袭"
    },
    "30":{
      "inid":30,
      "type":2,
      "vip":0,
      "level":65,
      "name":"座驾商店"
    },
    "31":{
      "inid":31,
      "type":2,
      "vip":0,
      "level":15,
      "name":"声望商店"
    },
    "32":{
      "inid":32,
      "type":1,
      "vip":1,
      "level":1,
      "name":"关卡直接挑战BOSS"
    },
    "33":{
      "inid":33,
      "type":1,
      "vip":1,
      "level":1,
      "name":"兵工厂扫荡功能"
    },
    "34":{
      "inid":34,
      "type":1,
      "vip":5,
      "level":1,
      "name":"自动侦查功能"
    },
    "35":{
      "inid":35,
      "type":1,
      "vip":5,
      "level":1,
      "name":"军团高级建设功能"
    },
    "36":{
      "inid":36,
      "type":1,
      "vip":6,
      "level":1,
      "name":"重置跨服战斗"
    },
    "37":{
      "inid":37,
      "type":3,
      "vip":7,
      "level":70,
      "name":"解锁资源掠夺一键扫荡功能"
    },
    "38":{
      "inid":38,
      "type":3,
      "vip":8,
      "level":95,
      "name":"军团副本快速战斗功能"
    },
    "39":{
      "inid":39,
      "type":3,
      "vip":9,
      "level":100,
      "name":"军团跨服BOSS快速战斗功能"
    },
    "40":{
      "inid":40,
      "type":1,
      "vip":10,
      "level":1,
      "name":"额外解锁2个协同作战位置"
    },
    "41":{
      "inid":41,
      "type":1,
      "vip":0,
      "level":50,
      "name":"军事活动-精英副本"
    }
  }