
/**
 ** @Author:pandayu
 ** @Version:1.0
 ** @DateTime:2018-09-09
 ** @Project:pandaCard CardGame
 ** @Contact: QQ:815099602
 **/
 var MISSIONTYPECFG = {
    "login":{
      "Trigger":"login",
      "id":1,
      "type":1,
      "des":"每日登录游戏"
    },
    "arsenal_challenge":{
      "Trigger":"arsenal_challenge",
      "id":2,
      "type":1,
      "des":"进入兵工厂"
    },
    "arsenal_win":{
      "Trigger":"arsenal_win",
      "id":3,
      "type":1,
      "des":"兵工厂胜利"
    },
    "depot_num":{
      "Trigger":"depot_num",
      "id":4,
      "type":2,
      "des":"拥有装备数量"
    },
    "depot_strengthen":{
      "Trigger":"depot_strengthen",
      "id":5,
      "type":1,
      "des":"强化装备次数"
    },
    "depot_strengthen_maxlev":{
      "Trigger":"depot_strengthen_maxlev",
      "id":6,
      "type":2,
      "des":"装备最高强化等级"
    },
    "depot_refine":{
      "Trigger":"depot_refine",
      "id":7,
      "type":1,
      "des":"精炼装备次数"
    },
    "depot_refine_maxlev":{
      "Trigger":"depot_refine_maxlev",
      "id":8,
      "type":2,
      "des":"装备最高精炼等级"
    },
    "soldiers_num":{
      "Trigger":"soldiers_num",
      "id":9,
      "type":2,
      "des":"拥有士兵数量"
    },
    "soldier_levup":{
      "Trigger":"soldier_levup",
      "id":10,
      "type":1,
      "des":"士兵升级次数"
    },
    "soldier_maxlev":{
      "Trigger":"soldier_maxlev",
      "id":11,
      "type":2,
      "des":"士兵最高等级"
    },
    "both":{
      "Trigger":"both",
      "id":12,
      "type":1,
      "des":"参加对战次数"
    },
    "both_win":{
      "Trigger":"both_win",
      "id":13,
      "type":1,
      "des":"战胜对战对手次数"
    },
    "shop_buy":{
      "Trigger":"shop_buy",
      "id":14,
      "type":1,
      "des":"商店购买物品次数"
    },
    "exchange":{
      "Trigger":"exchange",
      "id":15,
      "type":1,
      "des":"钻石兑换金币次数"
    },
    "explore":{
      "Trigger":"explore",
      "id":16,
      "type":1,
      "des":"探险次数"
    },
    "battle_fast":{
      "Trigger":"battle_fast",
      "id":17,
      "type":1,
      "des":"快速战斗次数"
    },
    "alliancegirl_tryst":{
      "Trigger":"alliancegirl_tryst",
      "id":18,
      "type":1,
      "des":"佳人约会次数"
    },
    "alliancegirl_getaward":{
      "Trigger":"alliancegirl_getaward",
      "id":19,
      "type":1,
      "des":"佳人推到次数"
    },
    "replica_high_part_pass":{
      "Trigger":"replica_high_part_pass",
      "id":20,
      "type":1,
      "des":"精英副本小关卡胜利次数"
    },
    "replica_high_pass":{
      "Trigger":"replica_high_pass",
      "id":21,
      "type":1,
      "des":"通过精英副本大关卡次数（大关卡中4个小关卡胜利就算大关卡通关）"
    },
    "replica_high_starnum":{
      "Trigger":"replica_high_starnum",
      "id":22,
      "type":2,
      "des":"精英副本获得总星数"
    },
    "boss_challenge":{
      "Trigger":"boss_challenge",
      "id":23,
      "type":1,
      "des":"攻打BOSS次数"
    },
    "boss_challenge_kill":{
      "Trigger":"boss_challenge_kill",
      "id":24,
      "type":1,
      "des":"击杀BOSS个数"
    },
    "commander_maxlev":{
      "Trigger":"commander_maxlev",
      "id":25,
      "type":2,
      "des":"指挥官最高等级"
    },
    "activity_value":{
      "Trigger":"activity_value",
      "id":26,
      "type":2,
      "des":"活跃值最高点数"
    },
    "Online_time":{
      "Trigger":"Online_time",
      "id":27,
      "type":2,
      "des":"在线时间"
    },
    "pay_day":{
      "Trigger":"pay_day",
      "id":28,
      "type":2,
      "des":"每日累计充值"
    },
    "pay_ac_all":{
      "Trigger":"pay_ac_all",
      "id":29,
      "type":1,
      "des":"活动内累计充值"
    },
    "consumer_day":{
      "Trigger":"consumer_day",
      "id":30,
      "type":2,
      "des":"每日累计消费"
    },
    "consumer_all":{
      "Trigger":"consumer_all",
      "id":31,
      "type":2,
      "des":"活动内累计消费"
    },
    "diamond_exchange":{
      "Trigger":"diamond_exchange",
      "id":32,
      "type":1,
      "des":"钻石购买物品"
    },
    "skill_base_level":{
      "Trigger":"skill_base_level",
      "id":33,
      "type":2,
      "des":"指挥官基础攻击等级"
    },
    "depot_strengthen_great_lev":{
      "Trigger":"depot_strengthen_great_lev",
      "id":34,
      "type":2,
      "des":"强化大师等级达到"
    },
    "depot_refine_great_lev":{
      "Trigger":"depot_refine_great_lev",
      "id":35,
      "type":2,
      "des":"精炼大师等级达到"
    },
    "pay_all":{
      "Trigger":"pay_all",
      "id":36,
      "type":2,
      "des":"累计充值多少钻"
    },
    "shop_refresh":{
      "Trigger":"shop_refresh",
      "id":37,
      "type":2,
      "des":"商店累计刷新多少次"
    },
    "stage_max":{
      "Trigger":"stage_max",
      "id":38,
      "type":2,
      "des":"通过第多少关"
    },
    "opt_tw":{
      "Trigger":"opt_tw",
      "id":39,
      "type":2,
      "des":"领取操作计数"
    },
    "open_online_time":{
      "Trigger":"open_online_time",
      "id":40,
      "type":2,
      "des":"开服在线时间"
    },
    "arena_num":{
      "Trigger":"arena_num",
      "id":41,
      "type":1,
      "des":"参与竞技场次数"
    },
    "pay_daynum":{
      "Trigger":"pay_daynum",
      "id":42,
      "type":1,
      "des":"活动内满足条件的充值天数"
    },
    "pay_oneday":{
      "Trigger":"pay_oneday",
      "id":43,
      "type":1,
      "des":"每日单笔充值大于等于某一值"
    }
  }