
/**
 ** @Author:pandayu
 ** @Version:1.0
 ** @DateTime:2018-09-09
 ** @Project:pandaCard CardGame
 ** @Contact: QQ:815099602
 **/
 var RANDOMNAMECFG = {
    "1":{
      "id":1,
      "familyname":"史密斯",
      "nanname":"雷欧",
      "nvname":"蕾欧娜"
    },
    "2":{
      "id":2,
      "familyname":"约翰逊",
      "nanname":"卢卡斯",
      "nvname":"雷奥妮"
    },
    "3":{
      "id":3,
      "familyname":"威廉姆斯",
      "nanname":"卢卡",
      "nvname":"汉娜"
    },
    "4":{
      "id":4,
      "familyname":"布朗",
      "nanname":"迪姆",
      "nvname":"米娅"
    },
    "5":{
      "id":5,
      "familyname":"琼斯",
      "nanname":"费恩",
      "nvname":"蕾娜"
    },
    "6":{
      "id":6,
      "familyname":"米勒",
      "nanname":"约纳斯",
      "nvname":"安娜"
    },
    "7":{
      "id":7,
      "familyname":"戴维斯",
      "nanname":"菲利克斯",
      "nvname":"雷娅"
    },
    "8":{
      "id":8,
      "familyname":"加西亚",
      "nanname":"路易斯",
      "nvname":"露易丝"
    },
    "9":{
      "id":9,
      "familyname":"罗德里格",
      "nanname":"保罗",
      "nvname":"艾米丽"
    },
    "10":{
      "id":10,
      "familyname":"威尔逊",
      "nanname":"马克西米",
      "nvname":"拉拉"
    },
    "11":{
      "id":11,
      "familyname":"马丁内兹",
      "nanname":"尤利安",
      "nvname":"朱利安"
    },
    "12":{
      "id":12,
      "familyname":"安德森",
      "nanname":"尼可拉斯",
      "nvname":"莎拉"
    },
    "13":{
      "id":13,
      "familyname":"泰勒",
      "nanname":"马克斯",
      "nvname":"劳拉"
    },
    "14":{
      "id":14,
      "familyname":"托马斯",
      "nanname":"本",
      "nvname":"莉莉"
    },
    "15":{
      "id":15,
      "familyname":"马丁内兹",
      "nanname":"艾欧利亚",
      "nvname":"伊利亚"
    },
    "16":{
      "id":16,
      "familyname":"杰克逊",
      "nanname":"菲利普",
      "nvname":"丽娜"
    },
    "17":{
      "id":17,
      "familyname":"汤普森",
      "nanname":"雅尼克",
      "nvname":"玛丽"
    },
    "18":{
      "id":18,
      "familyname":"怀特",
      "nanname":"雅各布",
      "nvname":"苏菲"
    },
    "19":{
      "id":19,
      "familyname":"李",
      "nanname":"迈克尔",
      "nvname":"奈乐"
    },
    "20":{
      "id":20,
      "familyname":"洛佩兹",
      "nanname":"伊桑",
      "nvname":"约翰娜"
    },
    "21":{
      "id":21,
      "familyname":"哈里斯",
      "nanname":"乔舒亚",
      "nvname":"索菲亚"
    },
    "22":{
      "id":22,
      "familyname":"克拉克",
      "nanname":"亚历山大",
      "nvname":"丽莎"
    },
    "23":{
      "id":23,
      "familyname":"鲁滨逊",
      "nanname":"安东尼",
      "nvname":"玛雅"
    },
    "24":{
      "id":24,
      "familyname":"沃克",
      "nanname":"威廉",
      "nvname":"塞西莉亚"
    },
    "25":{
      "id":25,
      "familyname":"佩雷斯",
      "nanname":"克里斯托",
      "nvname":"狄斯梦娜"
    },
    "26":{
      "id":26,
      "familyname":"霍尔",
      "nanname":"杰顿",
      "nvname":"菲莉茜亚"
    },
    "27":{
      "id":27,
      "familyname":"杨",
      "nanname":"安德鲁",
      "nvname":"优利卡"
    },
    "28":{
      "id":28,
      "familyname":"桑切斯",
      "nanname":"约瑟夫",
      "nvname":"瑰拉"
    },
    "29":{
      "id":29,
      "familyname":"刘易斯",
      "nanname":"诺阿",
      "nvname":"克罗迪雅"
    },
    "30":{
      "id":30,
      "familyname":"冈萨雷斯",
      "nanname":"艾丹",
      "nvname":"英帝拉"
    },
    "31":{
      "id":31,
      "familyname":"赫尔南德",
      "nanname":"詹姆斯",
      "nvname":"义哲法"
    },
    "32":{
      "id":32,
      "familyname":"艾伦",
      "nanname":"赖恩",
      "nvname":"戴妮"
    },
    "33":{
      "id":33,
      "familyname":"金",
      "nanname":"洛根",
      "nvname":"安"
    },
    "34":{
      "id":34,
      "familyname":"赖特",
      "nanname":"约翰",
      "nvname":"克洛哀"
    },
    "35":{
      "id":35,
      "familyname":"斯科特",
      "nanname":"内森",
      "nvname":"丝萝"
    },
    "36":{
      "id":36,
      "familyname":"格林",
      "nanname":"伊莱贾",
      "nvname":"艾丝"
    },
    "37":{
      "id":37,
      "familyname":"贝克",
      "nanname":"克里斯",
      "nvname":"赛丽娜"
    },
    "38":{
      "id":38,
      "familyname":"亚当斯",
      "nanname":"加布里尔",
      "nvname":"爱玛黎丝"
    },
    "39":{
      "id":39,
      "familyname":"纳尔逊",
      "nanname":"本杰明",
      "nvname":"赛拉"
    },
    "40":{
      "id":40,
      "familyname":"拉米瑞兹",
      "nanname":"乔纳森",
      "nvname":"卡丽妲"
    },
    "41":{
      "id":41,
      "familyname":"希尔",
      "nanname":"泰勒",
      "nvname":"艾莉娜"
    },
    "42":{
      "id":42,
      "familyname":"罗伯茨",
      "nanname":"塞缪尔",
      "nvname":"爱莱塔"
    },
    "43":{
      "id":43,
      "familyname":"菲利普斯",
      "nanname":"尼古拉斯",
      "nvname":"菲欧娜"
    },
    "44":{
      "id":44,
      "familyname":"卡特",
      "nanname":"加文",
      "nvname":"朵洛莉丝"
    },
    "45":{
      "id":45,
      "familyname":"米切尔",
      "nanname":"迪兰",
      "nvname":"艾薇"
    },
    "46":{
      "id":46,
      "familyname":"特纳",
      "nanname":"杰克逊",
      "nvname":"琴"
    },
    "47":{
      "id":47,
      "familyname":"埃文斯",
      "nanname":"布兰顿",
      "nvname":"珍"
    },
    "48":{
      "id":48,
      "familyname":"托雷斯",
      "nanname":"凯勒布",
      "nvname":"琼"
    },
    "49":{
      "id":49,
      "familyname":"坎贝尔",
      "nanname":"杰克逊",
      "nvname":"乔安娜"
    },
    "50":{
      "id":50,
      "familyname":"摩尔",
      "nanname":"布兰顿",
      "nvname":"维纳"
    },
    "51":{
      "id":51,
      "familyname":"伯纳德",
      "nanname":"凯勒布",
      "nvname":"翠丝特"
    },
    "52":{
      "id":52,
      "familyname":"斯密特",
      "nanname":"梅森",
      "nvname":"菲碧"
    },
    "53":{
      "id":53,
      "familyname":"施耐德",
      "nanname":"安吉尔",
      "nvname":"埃玛"
    },
    "54":{
      "id":54,
      "familyname":"费舍尔",
      "nanname":"艾萨克",
      "nvname":"伊莎贝拉"
    },
    "55":{
      "id":55,
      "familyname":"韦伯",
      "nanname":"埃文",
      "nvname":"奥利维亚"
    },
    "56":{
      "id":56,
      "familyname":"舒尔茨",
      "nanname":"杰克",
      "nvname":"伊丽莎白"
    },
    "57":{
      "id":57,
      "familyname":"霍夫曼",
      "nanname":"凯文",
      "nvname":"艾比盖尔"
    },
    "58":{
      "id":58,
      "familyname":"穆勒",
      "nanname":"乔斯",
      "nvname":"克西丝"
    },
    "59":{
      "id":59,
      "familyname":"迈尔",
      "nanname":"艾塞亚",
      "nvname":"艾丽萨"
    },
    "60":{
      "id":60,
      "familyname":"梅耶",
      "nanname":"卢克",
      "nvname":"娜塔莉"
    },
    "61":{
      "id":61,
      "familyname":"卡尔森",
      "nanname":"兰登",
      "nvname":"阿什丽"
    },
    "62":{
      "id":62,
      "familyname":"尼尔森",
      "nanname":"贾斯可",
      "nvname":"艾拉"
    },
    "63":{
      "id":63,
      "familyname":"埃里克松",
      "nanname":"卢卡斯",
      "nvname":"格丽丝"
    },
    "64":{
      "id":64,
      "familyname":"拉尔森",
      "nanname":"扎克里",
      "nvname":"布丽安娜"
    },
    "65":{
      "id":65,
      "familyname":"奥尔松",
      "nanname":"乔丹",
      "nvname":"海丽"
    },
    "66":{
      "id":66,
      "familyname":"佩尔松",
      "nanname":"罗伯特",
      "nvname":"维多丽娅"
    },
    "67":{
      "id":67,
      "familyname":"斯文松",
      "nanname":"艾伦",
      "nvname":"凯拉"
    },
    "68":{
      "id":68,
      "familyname":"古斯塔夫",
      "nanname":"布雷登",
      "nvname":"丽莲"
    },
    "69":{
      "id":69,
      "familyname":"佩特森",
      "nanname":"托马斯",
      "nvname":"凯丽"
    },
    "70":{
      "id":70,
      "familyname":"汉森",
      "nanname":"卡梅伦",
      "nvname":"艾丽森"
    },
    "71":{
      "id":71,
      "familyname":"林德伯格",
      "nanname":"亨特",
      "nvname":"萨瓦娜"
    },
    "72":{
      "id":72,
      "familyname":"彼得逊",
      "nanname":"奥斯汀",
      "nvname":"内维娅"
    },
    "73":{
      "id":73,
      "familyname":"雅各布森",
      "nanname":"艾德里安",
      "nvname":"莱丽"
    },
    "74":{
      "id":74,
      "familyname":"墨菲",
      "nanname":"康纳",
      "nvname":"凯瑟琳"
    },
    "75":{
      "id":75,
      "familyname":"凯利",
      "nanname":"欧文",
      "nvname":"戴斯蒂尼"
    },
    "76":{
      "id":76,
      "familyname":"沃尔什",
      "nanname":"艾丹",
      "nvname":"凯特琳"
    },
    "77":{
      "id":77,
      "familyname":"奥布莱恩",
      "nanname":"贾森",
      "nvname":"伊芙琳"
    },
    "78":{
      "id":78,
      "familyname":"拜恩",
      "nanname":"怀亚特",
      "nvname":"杰西卡"
    },
    "79":{
      "id":79,
      "familyname":"莱恩",
      "nanname":"查尔斯",
      "nvname":"麦德琳"
    },
    "80":{
      "id":80,
      "familyname":"奥康纳",
      "nanname":"卡特",
      "nvname":"艾丽阿娜"
    },
    "81":{
      "id":81,
      "familyname":"奥尼尔",
      "nanname":"胡安",
      "nvname":"阿米莉亚"
    },
    "82":{
      "id":82,
      "familyname":"奥莱利",
      "nanname":"蔡斯",
      "nvname":"安吉丽娜"
    },
    "83":{
      "id":83,
      "familyname":"麦卡锡",
      "nanname":"迪格",
      "nvname":"卡米拉"
    },
    "84":{
      "id":84,
      "familyname":"肯尼迪",
      "nanname":"杰里迈亚",
      "nvname":"詹妮芙"
    },
    "85":{
      "id":85,
      "familyname":"林奇",
      "nanname":"布罗迪",
      "nvname":"梅兰妮"
    },
    "86":{
      "id":86,
      "familyname":"莫雷",
      "nanname":"泽维尔",
      "nvname":"夏洛特"
    },
    "87":{
      "id":87,
      "familyname":"昆",
      "nanname":"亚当",
      "nvname":"菲丝"
    },
    "88":{
      "id":88,
      "familyname":"斯米特",
      "nanname":"塞巴斯蒂",
      "nvname":"伊莎贝尔"
    },
    "89":{
      "id":89,
      "familyname":"德波尔",
      "nanname":"海顿",
      "nvname":"佐伊"
    },
    "90":{
      "id":90,
      "familyname":"亚历山大",
      "nanname":"杰西斯",
      "nvname":"阿娃"
    },
    "91":{
      "id":91,
      "familyname":"艾伯特",
      "nanname":"伊恩",
      "nvname":"米厄"
    },
    "92":{
      "id":92,
      "familyname":"安德鲁",
      "nanname":"特里斯坦",
      "nvname":"艾丽萨"
    },
    "93":{
      "id":93,
      "familyname":"安迪",
      "nanname":"特里斯坦",
      "nvname":"劳伦"
    },
    "94":{
      "id":94,
      "familyname":"布鲁斯",
      "nanname":"肖恩",
      "nvname":"丽莲"
    },
    "95":{
      "id":95,
      "familyname":"查尔斯",
      "nanname":"科尔",
      "nvname":"萨瓦娜"
    },
    "96":{
      "id":96,
      "familyname":"布莱恩",
      "nanname":"亚历克斯",
      "nvname":"山德拉"
    },
    "97":{
      "id":97,
      "familyname":"丹尼尔",
      "nanname":"埃里克",
      "nvname":"麦西"
    },
    "98":{
      "id":98,
      "familyname":"丹尼斯",
      "nanname":"布赖恩",
      "nvname":"玲"
    },
    "99":{
      "id":99,
      "familyname":"德里克",
      "nanname":"杰登",
      "nvname":"乔丝琳"
    },
    "100":{
      "id":100,
      "familyname":"道格拉斯",
      "nanname":"卡森",
      "nvname":"丽安娜"
    }
  }